# Generated by Django 6.0.6 on 2026-07-12 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('daily_focus_goal_minutes', models.PositiveIntegerField(default=90)),
                ('weekly_focus_goal_minutes', models.PositiveIntegerField(default=450)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
