# Generated by Django 6.0.6 on 2026-07-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
