# Generated by Django 6.0.6 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userpreferences_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='dashboard_expanded_widgets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='dashboard_pinned_widgets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
