# Generated by Django 6.0.6 on 2026-07-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreferences_dashboard_expanded_widgets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='auto_detect_timezone',
            field=models.BooleanField(default=True),
        ),
    ]
