# Generated by Django 6.0.6 on 2026-07-12 10:43

from django.db import migrations, models


def backfill_session_metadata(apps, schema_editor):
    StudySession = apps.get_model("study", "StudySession")
    for session in StudySession.objects.select_related("subject", "section"):
        if session.completed:
            session.status = "completed"
        elif session.ended_at:
            session.status = "cancelled"
        else:
            session.status = "active"
        session.subject_title = session.subject.title if session.subject else ""
        session.section_title = session.section.title if session.section else ""
        session.planned_duration_seconds = session.duration_seconds if session.completed else 0
        session.save(update_fields=[
            "status",
            "subject_title",
            "section_title",
            "planned_duration_seconds",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='activity_type',
            field=models.CharField(choices=[('general', 'General study'), ('notes', 'Notes'), ('flashcards', 'Flashcards'), ('reading', 'Reading')], default='general', max_length=12),
        ),
        migrations.AddField(
            model_name='studysession',
            name='paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='planned_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='section_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studysession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='studysession',
            name='subject_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(backfill_session_metadata, migrations.RunPython.noop),
    ]
