# Generated by Django 6.0.6 on 2026-07-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='weekly_goal_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Target study time for this subject each week.'),
        ),
    ]
