# Generated by Django 6.0.6 on 2026-07-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='weekly_goal_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Optional weekly goal. Leave at zero to derive it from subjects.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='weekly_goal_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Optional weekly goal. Leave at zero to derive it from sections.'),
        ),
    ]
