# Generated by Django 6.0.6 on 2026-07-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notes/blocks/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='notes.note')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
