# Generated by Django 6.0.6 on 2026-07-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_noteblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteBlock',
        ),
    ]
