# Generated by Django 6.0.6 on 2026-07-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_note_image_remove_note_pdf_noteimage_notepdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteimage',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
