# Generated by Django 6.0.6 on 2026-07-11 17:12

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_noteimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteimage',
            name='image',
            field=models.ImageField(upload_to=notes.models.get_image_upload_path),
        ),
    ]
