# Generated by Django 6.0.6 on 2026-07-12 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_noteimage_image'),
        ('topics', '0002_subject_priority_subject_weekly_goal_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('section__isnull', False), ('subject__isnull', True)), models.Q(('section__isnull', True), ('subject__isnull', False)), _connector='OR'), name='note_has_exactly_one_context'),
        ),
    ]
