# Generated by Django 6.0.6 on 2026-07-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcard_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcards/answers/'),
        ),
    ]
