# Generated by Django 6.0.6 on 2026-07-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_flashcard_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
