# Generated by Django 6.0.6 on 2026-07-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcard_learned'),
        ('topics', '0002_subject_priority_subject_weekly_goal_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='ease_factor',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repetitions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('section__isnull', False), ('subject__isnull', True)), models.Q(('section__isnull', True), ('subject__isnull', False)), _connector='OR'), name='flashcard_has_exactly_one_context'),
        ),
    ]
