# Generated by Django 6.0.6 on 2026-07-28 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_study_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('kind', models.CharField(choices=[('plan', 'Plan'), ('deadline', 'Deadline')], default='plan', max_length=10)),
                ('target_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'Important')], db_index=True, default='normal', max_length=10)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed', 'target_at', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind', 'plan'), ('target_at__isnull', False), _connector='OR'), name='deadline_has_target_at')],
            },
        ),
    ]
