# Generated by Django 6.0.6 on 2026-08-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_task_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
